# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{abiquo-etk}
  s.version = "0.3.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergio Rubio"]
  s.date = %q{2010-09-21}
  s.description = %q{Tools to troubleshoot your Abiquo installation}
  s.email = %q{sergio@rubio.name}
  s.executables = ["aetk", "abiquo-check-16-install", "aetk-setup-rs", "aetk-setup-v2v", "aetk-setup-server"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    "VERSION",
     "lib/abiquo-etk.rb",
     "lib/checks/01detect_abiquo.rb",
     "lib/checks/abiquo_service.rb",
     "lib/checks/abiquo_version.rb",
     "lib/checks/components_installed.rb",
     "lib/checks/firewall.rb",
     "lib/checks/hv_passwords.rb",
     "lib/checks/install_type.rb",
     "lib/checks/java.rb",
     "lib/checks/mysql.rb",
     "lib/checks/nfs.rb",
     "lib/checks/os_version.rb",
     "lib/checks/virtualbox.rb",
     "scripts/setup_rs",
     "scripts/setup_v2v"
  ]
  s.homepage = %q{http://github.com/rubiojr/abiquo-etk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Abiquo Elite Toolkit}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

